apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-app.fullname" . }}-config
data:
  index.html: |
    <html>
      <body>
        <h1>{{ .Values.config.message }}</h1>
      </body>
    </html>
