ingressClassName: nginx

annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /

paths:
  - path: /jenkins
    pathType: Prefix
    service:
      name: jenkins-jenkins
      port: 8080

  - path: /prometheus
    pathType: Prefix
    service:
      name: prometheus
      port: 9090

  - path: /grafana
    pathType: Prefix
    service:
      name: grafana
      port: 3000
